Resources:
  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.UsersTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  
  QuickPairing:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.QuickPairingTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

  GamesArchive:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.GamesArchiveTableName}
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: S
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST

  Rooms:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.RoomsTableName}
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: S
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
        
  WebSocketConnections:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.WebSocketConnectionsTableName}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
  
  Problems:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ProblemsTableName}
        AttributeDefinitions:
          - AttributeName: problemId
            AttributeType: S
        KeySchema:
          - AttributeName: problemId
            KeyType: HASH
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST