Resources:
  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.UsersTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  
  QuickPairing:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.FastGamePlayersTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

  GamesArchive:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.GamesArchiveTableName}
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: S
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
  OpenRooms:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.OpenRoomsTableName}
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: S
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
  HiddenRooms:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.HiddenRoomsTableName}
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: S
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
        